# Configurazione del sito

title: "Alessio Roma"
description: "Composer"
url: "https://alessioroma.it"
baseurl: ""

# Informazioni personali
author:
  name: "Alessio Roma"
  email: "info@alessioroma.it"
  bio: "Compositore"

# Link ai social
social:
  instagram: "alessioroma.music"
  linkedin: "alessio-roma-1742a7317"

# Impostazioni tecniche
markdown: kramdown
permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigazione del sito
navigation:
  - title: "Biography"
    url: /biography/
  - title: "Works"
    url: /works/
  - title: "Events"
    url: /events/
  - title: "News"
    url: /news/
  - title: "Contacts"
    url: /contacts/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
